---
message: False
title: "Nederland Fires"
format: html
---

```{r}
library(tidyverse)
library(sf)
library(terra)
library(tmap)
library(tmaptools)
```


```{r}
# Set directory for folder
pre_fire_dir <- here::here("week6", "data", "LC80340322016189-SC20170128091153")

# Create a list of all images that have the extension .tif and contain the word band
pre_fire_bands <- list.files(pre_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
pre_fire_rast <- rast(pre_fire_bands)

# Read mask raster
pre_mask <- rast(here::here("week6", "data", "LC80340322016189-SC20170128091153", "LC80340322016189LGN00_cfmask_crop.tif"))
```



```{r}
# Set directory for folder
post_fire_dir <- here::here("week6", "data", "LC80340322016205-SC20170127160728")

# Create a list of all images that have the extension .tif and contain the word band
post_fire_bands <- list.files(post_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
post_fire_rast <- rast(post_fire_bands)

# Read mask raster
post_mask <- rast(here::here("week6", "data", "LC80340322016205-SC20170127160728", "LC80340322016205LGN00_cfmask_crop.tif"))
```


```{r}
nbr_fun <- function(nir, swir2){
    (nir - swir2)/(nir + swir2)
}
```

##2 Rename and mask the bands

```{r}
bands <- c("Aerosol", "Blue", "Green", "Red", "NIR", "SWIR1", "SWIR2")
names(pre_fire_rast) <- bands
names(post_fire_rast) <- bands

```


```{r}
# Set all cells with values greater than 0 to NA
pre_mask[pre_mask > 0] <- NA

# Subset raster based on mask
pre_fire_rast <- mask(pre_fire_rast, mask = pre_mask)

#View
plot(pre_fire_rast)

```


```{r}
# Set all cells with values greater than 0 to NA
post_mask[post_mask > 0] <- NA

# Subset raster based on mask
post_fire_rast <- mask(post_fire_rast, mask = post_mask)

# View raster
plot(post_fire_rast)
```


## 3) Plot true and false color composites
```{r}
pre1 <- plotRGB(pre_fire_rast, r=4, g=3, b = 2, stretch="lin", colNA = "black")
post1 <- plotRGB(post_fire_rast, r=4, g=3, b = 2, stretch="lin", colNA = "black")


```

```{r}
pre2 <- plotRGB(pre_fire_rast, r=7, g=5, b = 3, stretch="lin", colNA = "black")
post2 <- plotRGB(post_fire_rast, r=7, g=5, b = 3, stretch="lin", colNA = "black")
```


```{r}
pre_nbr_rast <- lapp(pre_fire_rast[[c(5, 7)]], fun = nbr_fun)

plot(pre_nbr_rast, main = "Cold Spring Pre-Fire NBR", colNA = "hotpink")


post_nbr_rast <- lapp(post_fire_rast[[c(5,7)]], fun = nbr_fun)

plot(post_nbr_rast, main = "Cold Spring Post-Fire NBR", colNA = "hotpink")
```
## 5) Plot difference of NBR

```{r}
diff_nbr <- pre_nbr_rast - post_nbr_rast

tm_shape(diff_nbr) +
  tm_raster(style = "equal", n = 6, 
            palette = "YlOrRd",
            title = "Difference NBR (dNBR)", colorNA = "black") +
  tm_layout(legend.outside = TRUE)

```


## 6) Bonus

```{r}
categories <- c("Enhanced Regrowth", "Unburned", "Low Severity", "Moderate Severity", "High Severity")


rcl_matrix <-matrix(c(-Inf, -.1, 1, 
                     -.1, .1, 2, 
                     0.1, 0.27, 3, 
                     0.27, 0.66, 4,
                     0.66, Inf, 5), 
             ncol = 3, byrow = TRUE)

reclass <- classify(diff_nbr, rcl=rcl_matrix)

tm_shape(reclass) +
  tm_raster(style = "cat",
            labels = c(categories, "missing"),
            palette = "YlOrRd",
            title = "Severity Level", colorNA = "black") +
  tm_layout(legend.outside = TRUE)

```

